name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  run_cargo_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Rustup install nightly
        run: rustup toolchain install nightly
      - name: Rustup install rustfmt
        run: rustup component add rustfmt --toolchain nightly
      - name: Run Cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: Run Cargo clippy
        run: cargo clippy --all-targets --all-features
  run_examples_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.10/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Build
        run: cargo build-sbf
      - name: Tests
        run: cargo test